/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201907221223.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V0_DCU_TELEPHONY_COMMON_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define V0_DCU_TELEPHONY_COMMON_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace DCU {
namespace Telephony {
namespace CommonTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<int32_t> SetPropertyErrorDeployment_t;

typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::MapDeployment<
        CommonAPI::SomeIP::StringDeployment,
        CommonAPI::SomeIP::VariantDeployment<
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<int64_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::StringDeployment
        >
    >
> AttributeListDeployment_t;

typedef CommonAPI::SomeIP::MapDeployment<
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::VariantDeployment<
        CommonAPI::SomeIP::IntegerDeployment<int32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<int64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::StringDeployment
    >
> StringVariantDictDeployment_t;

typedef CommonAPI::SomeIP::VariantDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::StringDeployment
> VariantTypeDeployment_t;


// typecollection-specific deployments

} // namespace CommonTypes_
} // namespace Telephony
} // namespace DCU
} // namespace v0

#endif // V0_DCU_TELEPHONY_COMMON_TYPES_SOMEIP_DEPLOYMENT_HPP_
