/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201907221223.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V0_DCU_TELEPHONY_Connection_Manager_SOMEIP_DEPLOYMENT_HPP_
#define V0_DCU_TELEPHONY_Connection_Manager_SOMEIP_DEPLOYMENT_HPP_

#include <v0/DCU/Telephony/CommonTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace DCU {
namespace Telephony {
namespace ConnectionManager_ {

// Interface-specific deployment types

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace ConnectionManager_
} // namespace Telephony
} // namespace DCU
} // namespace v0

#endif // V0_DCU_TELEPHONY_Connection_Manager_SOMEIP_DEPLOYMENT_HPP_
