/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201907221223.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v0/DCU/Telephony/ConnectionManagerSomeIPStubAdapter.hpp>
#include <v0/DCU/Telephony/ConnectionManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace DCU {
namespace Telephony {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createConnectionManagerSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< ConnectionManagerSomeIPStubAdapter<::v0::DCU::Telephony::ConnectionManagerStub>>(_address, _connection, _stub);
}

void initializeConnectionManagerSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:DCU.Telephony.ConnectionManager:v0_93:DCU.Telephony.ConnectionManager",
         0x18c6, 0x1801, 0, 93);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        ConnectionManager::getInterface(),
        &createConnectionManagerSomeIPStubAdapter);
}

INITIALIZER(registerConnectionManagerSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeConnectionManagerSomeIPStubAdapter);
}
} // namespace Telephony
} // namespace DCU
} // namespace v0
