/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * Describe data structures related to data connection functionality.
 */
#ifndef V0_DCU_TELEPHONY_Connection_Context_Types_HPP_
#define V0_DCU_TELEPHONY_Connection_Context_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace DCU {
namespace Telephony {

struct ConnectionContextTypes {



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "DCU.Telephony.ConnectionContextTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(0, 93);
}

}; // struct ConnectionContextTypes

} // namespace Telephony
} // namespace DCU
} // namespace v0

namespace CommonAPI {
}


namespace std {
}


// Compatibility
namespace v0_93 = v0;

#endif // V0_DCU_TELEPHONY_Connection_Context_Types_HPP_
